server:
  port: 8191

spring:
  application:
    name: shop-service
  datasource:
    url: jdbc:mysql://localhost:3307/shopService
    username: root
    password: audiLS450!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    MySQL5InnoDBDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8161/eureka
  instance:
    hostname: localhost